# Generated by Django 5.0.3 on 2024-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=True),
        ),
    ]
